/**
 * @webwaka/webhooks — Webhook SDK
 * Phase 6 / E34
 *
 * Provides:
 *   - HMAC-SHA256 payload signing (SEC-007)
 *   - TypeScript event payload types for all WebWaka domain events
 *
 * Usage:
 *   import { signWebhookPayload, verifyWebhookSignature } from '@webwaka/webhooks';
 *   import type { WebhookEvent, PaymentCompletedEvent } from '@webwaka/webhooks';
 */

export { signWebhookPayload, verifyWebhookSignature } from './signing.js';

export type {
  WebhookEnvelope,
  WebhookEventType,
  WebhookEvent,
  TemplateInstalledPayload,
  TemplatePurchasedPayload,
  WorkspaceMemberAddedPayload,
  PaymentCompletedPayload,
  KycApprovedPayload,
  KycRejectedPayload,
  BankTransferPayload,
  PosSaleCompletedPayload,
  PosFloatPayload,
  AirtimePayload,
  B2bRfqCreatedPayload,
  B2bBidPayload,
  B2bPoPayload,
  B2bInvoicePayload,
  B2bDisputePayload,
  ClaimPayload,
  NegotiationPayload,
  SupportTicketPayload,
  PartnerPayload,
  OnboardingPayload,
  TransportPayload,
  AiPayload,
  SocialPostPublishedPayload,
  SocialFollowPayload,
  TemplateInstalledEvent,
  TemplatePurchasedEvent,
  WorkspaceMemberAddedEvent,
  PaymentCompletedEvent,
  KycApprovedEvent,
  KycRejectedEvent,
  BankTransferCompletedEvent,
  BankTransferFailedEvent,
  BankTransferInitiatedEvent,
  BankTransferProcessingEvent,
  PosSaleCompletedEvent,
  PosFloatCreditedEvent,
  PosFloatDebitedEvent,
  AirtimePurchaseCompletedEvent,
  AirtimePurchaseFailedEvent,
  B2bRfqCreatedEvent,
  B2bBidSubmittedEvent,
  B2bBidAcceptedEvent,
  B2bPoIssuedEvent,
  B2bPoDeliveredEvent,
  B2bInvoiceRaisedEvent,
  B2bDisputeRaisedEvent,
  ClaimSubmittedEvent,
  ClaimApprovedEvent,
  ClaimRejectedEvent,
  ClaimAdvancedEvent,
  NegotiationSessionStartedEvent,
  NegotiationAcceptedEvent,
  NegotiationRejectedEvent,
  NegotiationSessionExpiredEvent,
  SupportTicketCreatedEvent,
  SupportTicketResolvedEvent,
  SupportTicketClosedEvent,
  PartnerOnboardedEvent,
  PartnerApplicationApprovedEvent,
  PartnerApplicationRejectedEvent,
  PartnerSubPartnerCreatedEvent,
  OnboardingStartedEvent,
  OnboardingCompletedEvent,
  OnboardingStalledEvent,
  TransportBookingCreatedEvent,
  TransportBookingConfirmedEvent,
  TransportTripStartedEvent,
  TransportTripCompletedEvent,
  TransportBookingCancelledEvent,
  AiResponseGeneratedEvent,
  AiBudgetWarningEvent,
  AiBudgetExhaustedEvent,
  SocialPostPublishedEvent,
  SocialFollowCreatedEvent,
} from './types.js';
