import type { OpticianProfile, CreateOpticianInput, OpticianFSMState, VisionTestRecord, EyewearOrder } from './types.js';
interface D1Like { prepare(s: string): { bind(...v: unknown[]): { run(): Promise<{ success: boolean }>; first<T>(): Promise<T | null>; all<T>(): Promise<{ results: T[] }>; }; }; }
function toProfile(r: Record<string, unknown>): OpticianProfile { return { id: r['id'] as string, workspaceId: r['workspace_id'] as string, tenantId: r['tenant_id'] as string, businessName: r['business_name'] as string, coaLicence: r['coa_licence'] as string|null, mdcnVerification: r['mdcn_verification'] as string|null, cacRc: r['cac_rc'] as string|null, status: r['status'] as OpticianFSMState, createdAt: r['created_at'] as number, updatedAt: r['updated_at'] as number }; }
function toTest(r: Record<string, unknown>): VisionTestRecord { return { id: r['id'] as string, profileId: r['profile_id'] as string, tenantId: r['tenant_id'] as string, patientRefId: r['patient_ref_id'] as string, testDate: r['test_date'] as number, rightEyeSphX100: r['right_eye_sph_x100'] as number, leftEyeSphX100: r['left_eye_sph_x100'] as number, rightEyeCylX100: r['right_eye_cyl_x100'] as number|null, leftEyeCylX100: r['left_eye_cyl_x100'] as number|null, pdMmX10: r['pd_mm_x10'] as number|null, optometristRefId: r['optometrist_ref_id'] as string|null, requiresReferral: Boolean(r['requires_referral']), notes: r['notes'] as string|null, consultationFeeKobo: r['consultation_fee_kobo'] as number, createdAt: r['created_at'] as number }; }
function toOrder(r: Record<string, unknown>): EyewearOrder { return { id: r['id'] as string, profileId: r['profile_id'] as string, tenantId: r['tenant_id'] as string, patientRefId: r['patient_ref_id'] as string, testId: r['test_id'] as string|null, eyewearType: r['eyewear_type'] as EyewearOrder['eyewearType'], frameBrand: r['frame_brand'] as string|null, lensBrand: r['lens_brand'] as string|null, totalKobo: r['total_kobo'] as number, depositKobo: r['deposit_kobo'] as number, orderDate: r['order_date'] as number, readyDate: r['ready_date'] as number|null, status: r['status'] as EyewearOrder['status'], createdAt: r['created_at'] as number, updatedAt: r['updated_at'] as number }; }
export class OpticianRepository {
  constructor(private readonly db: D1Like) {}
  async createProfile(input: CreateOpticianInput): Promise<OpticianProfile> {
    const id = input.id ?? crypto.randomUUID();
    await this.db.prepare(`INSERT INTO optician_profiles (id,workspace_id,tenant_id,business_name,coa_licence,mdcn_verification,cac_rc,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'seeded',unixepoch(),unixepoch())`).bind(id,input.workspaceId,input.tenantId,input.businessName,input.coaLicence??null,input.mdcnVerification??null,input.cacRc??null).run();
    const p = await this.findProfileById(id, input.tenantId); if (!p) throw new Error('[optician] create failed'); return p;
  }
  async findProfileById(id: string, tenantId: string): Promise<OpticianProfile|null> { const r = await this.db.prepare('SELECT * FROM optician_profiles WHERE id=? AND tenant_id=?').bind(id,tenantId).first<Record<string,unknown>>(); return r ? toProfile(r) : null; }
  async findProfileByWorkspace(workspaceId: string, tenantId: string): Promise<OpticianProfile|null> { const r = await this.db.prepare('SELECT * FROM optician_profiles WHERE workspace_id=? AND tenant_id=?').bind(workspaceId,tenantId).first<Record<string,unknown>>(); return r ? toProfile(r) : null; }
  async transitionStatus(id: string, tenantId: string, to: OpticianFSMState, fields?: { coaLicence?: string }): Promise<OpticianProfile> {
    const extraClauses: string[] = []; const extraBinds: unknown[] = [];
    if (fields?.coaLicence) { extraClauses.push('coa_licence = ?'); extraBinds.push(fields.coaLicence); }
    await this.db.prepare(`UPDATE optician_profiles SET status=?${extraClauses.length ? ', ' + extraClauses.join(', ') : ''}, updated_at=unixepoch() WHERE id=? AND tenant_id=?`).bind(to,...extraBinds,id,tenantId).run();
    const p = await this.findProfileById(id, tenantId); if (!p) throw new Error('[optician] not found'); return p;
  }
  async recordVisionTest(profileId: string, tenantId: string, input: { patientRefId: string; testDate: number; rightEyeSphX100: number; leftEyeSphX100: number; rightEyeCylX100?: number; leftEyeCylX100?: number; pdMmX10?: number; optometristRefId?: string; requiresReferral?: boolean; notes?: string; consultationFeeKobo?: number }): Promise<VisionTestRecord> {
    if (!Number.isInteger(input.rightEyeSphX100) || !Number.isInteger(input.leftEyeSphX100)) throw new Error('Sphere values must be integers ×100 (no floats)');
    const id = crypto.randomUUID();
    await this.db.prepare('INSERT INTO vision_test_records (id,profile_id,tenant_id,patient_ref_id,test_date,right_eye_sph_x100,left_eye_sph_x100,right_eye_cyl_x100,left_eye_cyl_x100,pd_mm_x10,optometrist_ref_id,requires_referral,notes,consultation_fee_kobo,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,unixepoch())').bind(id,profileId,tenantId,input.patientRefId,input.testDate,input.rightEyeSphX100,input.leftEyeSphX100,input.rightEyeCylX100??null,input.leftEyeCylX100??null,input.pdMmX10??null,input.optometristRefId??null,input.requiresReferral?1:0,input.notes??null,input.consultationFeeKobo??0).run();
    const r = await this.db.prepare('SELECT * FROM vision_test_records WHERE id=? AND tenant_id=?').bind(id,tenantId).first<Record<string,unknown>>(); if (!r) throw new Error('[optician] test create failed'); return toTest(r);
  }
  async listVisionTests(profileId: string, tenantId: string): Promise<VisionTestRecord[]> { const { results } = await this.db.prepare('SELECT * FROM vision_test_records WHERE profile_id=? AND tenant_id=? ORDER BY test_date DESC').bind(profileId,tenantId).all<Record<string,unknown>>(); return results.map(toTest); }
  async createEyewearOrder(profileId: string, tenantId: string, input: { patientRefId: string; testId?: string; eyewearType: string; frameBrand?: string; lensBrand?: string; totalKobo: number; depositKobo?: number; orderDate: number }): Promise<EyewearOrder> {
    if (!Number.isInteger(input.totalKobo)) throw new Error('total_kobo must be integer (P9)');
    const id = crypto.randomUUID();
    await this.db.prepare('INSERT INTO eyewear_orders (id,profile_id,tenant_id,patient_ref_id,test_id,eyewear_type,frame_brand,lens_brand,total_kobo,deposit_kobo,order_date,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,\'pending\',unixepoch(),unixepoch())').bind(id,profileId,tenantId,input.patientRefId,input.testId??null,input.eyewearType,input.frameBrand??null,input.lensBrand??null,input.totalKobo,input.depositKobo??0,input.orderDate).run();
    const r = await this.db.prepare('SELECT * FROM eyewear_orders WHERE id=? AND tenant_id=?').bind(id,tenantId).first<Record<string,unknown>>(); if (!r) throw new Error('[optician] order create failed'); return toOrder(r);
  }
  async listEyewearOrders(profileId: string, tenantId: string): Promise<EyewearOrder[]> { const { results } = await this.db.prepare('SELECT * FROM eyewear_orders WHERE profile_id=? AND tenant_id=? ORDER BY order_date DESC').bind(profileId,tenantId).all<Record<string,unknown>>(); return results.map(toOrder); }
}
export function guardSeedToClaimed(_p: OpticianProfile): { allowed: boolean; reason?: string } { return { allowed: true }; }
