"""
Generate the S05 batch 5 SQL migration for Lagos State House of Assembly members
(10th Assembly, 2023–2027 session).

Sources:
  - Primary: Wikipedia "List of members of the Lagos State House of Assembly (2023–2027)"
    https://en.wikipedia.org/wiki/List_of_members_of_the_Lagos_State_House_of_Assembly_(2023%E2%80%932027)
    (Wikipedia cites official Lagos State House of Assembly website and Nigerian Tribune)
    Confidence: editorial_verified
  - Cross-reference: Lagos State House of Assembly official website
    https://www.lagoshouseofassembly.gov.ng/meet-our-members/
    (not directly scraped but cited by Wikipedia as source)

Notes:
  - Only Lagos State has a consolidated Wikipedia member list for the 2023–2027 session;
    all other 35 states are deferred pending per-state official source access.
  - Constituency resolution: Wikipedia uses "Constituency NN" (e.g. "Agege 01") while INEC
    S03 jurisdiction seed uses uppercase Roman numerals (e.g. "AGEGE I"). The mapping is
    documented per-row in the normalized artifact.
  - "Somolu" in Wikipedia maps to "SHOMOLU" in INEC (official INEC spelling).
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
SOURCE_DIR = ROOT / "infra" / "db" / "seed" / "sources"
DATE = "20260422"

TENANT_ID = "tenant_platform_seed"
WORKSPACE_ID = "workspace_platform_seed_discovery"
SEED_RUN_ID = "seed_run_s05_political_foundation_lagos_assembly_20260422"
SOURCE_WP_ID = "seed_source_wikipedia_lagos_assembly_2023_20260422"

NORMALIZED_PATH = SOURCE_DIR / f"s05_lagos_assembly_normalized_{DATE}.json"
MIGRATION_PATH = ROOT / "infra" / "db" / "migrations" / "0313_political_lagos_assembly_seed.sql"
API_MIGRATION_PATH = ROOT / "apps" / "api" / "migrations" / "0313_political_lagos_assembly_seed.sql"
SEED_MIRROR_PATH = ROOT / "infra" / "db" / "seed" / "0014_political_lagos_assembly.sql"

TERM_LAGOS_ASSEMBLY_ID = "term_ng_lagos_state_assembly_10th_2023_2027"
STATE_PLACE_ID = "place_state_lagos"

PARTY_IDS = {
    "APC": "org_political_party_apc",
    "LP":  "org_political_party_lp",
}


def stable_id(prefix: str, key: str) -> str:
    h = hashlib.sha256(key.encode()).hexdigest()[:16]
    return f"{prefix}_{h}"


def name_key(full_name: str) -> str:
    return re.sub(r"[^a-z0-9]", "_", full_name.lower()).strip("_")


def emit_sql(members: list[dict]) -> str:
    lines: list[str] = []

    def w(*parts: str) -> None:
        lines.append("".join(parts))

    w("-- ============================================================")
    w("-- S05 Batch 5: Lagos State House of Assembly (10th Assembly, 2023-2027)")
    w("-- Generated by infra/db/seed/scripts/generate_s05_lagos_assembly_sql.py")
    w("-- Source: Wikipedia 'List of members of the Lagos State House of Assembly")
    w("--         (2023-2027)' (citing official Lagos HoA website + Nigerian Tribune)")
    w("-- 40 members, 40/40 constituencies resolved against S03 jurisdiction seed")
    w("-- ============================================================")
    w()
    w("BEGIN TRANSACTION;")
    w()

    # ── Term ─────────────────────────────────────────────────────────────────
    w("-- Term: Lagos State Assembly 10th Assembly 2023-2027")
    w("INSERT OR IGNORE INTO terms (id, label, election_cycle_id, level, office_type,")
    w("  jurisdiction_place_id, start_date, end_date, created_at, updated_at)")
    w("VALUES (")
    w(f"  '{TERM_LAGOS_ASSEMBLY_ID}',")
    w("  'Lagos State Assembly (10th Assembly, 2023-2027)',")
    w("  'cycle_ng_state_general_2023',")
    w("  'state',")
    w("  'state_assembly_member',")
    w(f"  '{STATE_PLACE_ID}',")
    w("  '2023-06-06',")
    w("  '2027-06-05',")
    w("  unixepoch(), unixepoch()")
    w(");")
    w()

    # ── Seed run / source / artifact ─────────────────────────────────────────
    w("-- S04 seed run and source")
    w("INSERT OR IGNORE INTO seed_runs (id, label, phase, status, started_at, completed_at)")
    w(f"VALUES ('{SEED_RUN_ID}', 'S05 Batch 5 – Lagos State Assembly 2023-2027',")
    w("  'S05', 'completed', unixepoch(), unixepoch());")
    w()

    SOURCE_URL = "https://en.wikipedia.org/wiki/List_of_members_of_the_Lagos_State_House_of_Assembly_(2023%E2%80%932027)"
    SOURCE_URL2 = "https://www.lagoshouseofassembly.gov.ng/meet-our-members/"
    w("INSERT OR IGNORE INTO seed_sources (id, label, source_type, url, confidence_tier, notes)")
    w(f"VALUES ('{SOURCE_WP_ID}',")
    w("  'Wikipedia – List of members of the Lagos State House of Assembly (2023–2027)',")
    w("  'editorial_aggregator',")
    w(f"  '{SOURCE_URL}',")
    w("  'editorial_verified',")
    w("  'Wikipedia page cites the official Lagos State House of Assembly website")
    w(f"   ({SOURCE_URL2}) and Nigerian Tribune as primary sources.');")
    w()
    artifact_id = "seed_artifact_s05_lagos_assembly_normalized_20260422"
    normalized_hash = hashlib.sha256(NORMALIZED_PATH.read_bytes()).hexdigest()
    w("INSERT OR IGNORE INTO seed_raw_artifacts (id, seed_run_id, artifact_type, file_path, content_hash, row_count, notes)")
    w(f"VALUES ('{artifact_id}',")
    w(f"  '{SEED_RUN_ID}',")
    w("  'normalized_json',")
    w(f"  'infra/db/seed/sources/s05_lagos_assembly_normalized_{DATE}.json',")
    w(f"  '{normalized_hash}',")
    w("  40,")
    w("  '40 Lagos State Assembly members, 40/40 constituencies resolved, 0 deferred');")
    w()

    # ── Members ───────────────────────────────────────────────────────────────
    for idx, m in enumerate(members, 1):
        full_name = m["full_name"]
        position  = m["position"]
        place_id  = m["place_id"]
        party_id  = m["party_id"]
        const_wp  = m["constituency_wp"]
        const_inec= m["constituency_inec"]
        party_abbr= m["party_abbrev"]

        dedup_key = f"ng_state_assembly_member|lagos|{const_inec.lower()}|2023"
        ind_id    = stable_id("ind", dedup_key)
        prof_id   = stable_id("prof", dedup_key)
        pp_id     = stable_id("pp", dedup_key)
        assign_id = stable_id("assign", dedup_key)
        aff_id    = stable_id("aff", dedup_key)
        dd_id     = stable_id("dd", dedup_key)
        ir_id     = stable_id("ir", dedup_key)
        im_id     = stable_id("im", dedup_key)
        pr_id     = stable_id("pr", dedup_key)
        es_id     = stable_id("es", dedup_key)
        enr_id    = stable_id("enr", dedup_key)
        se_id     = stable_id("se", dedup_key)

        # Title-case name
        display_name = full_name.title()

        w(f"-- {idx:02d}. {display_name} – {const_inec}")
        w("INSERT OR IGNORE INTO individuals")
        w("  (id, full_name, tenant_id, workspace_id, verification_state, created_at, updated_at)")
        w("VALUES (")
        w(f"  '{ind_id}', '{full_name.replace(chr(39), chr(39)*2)}',")
        w(f"  '{TENANT_ID}', '{WORKSPACE_ID}', 'editorial_verified', unixepoch(), unixepoch()")
        w(");")

        w("INSERT OR IGNORE INTO profiles")
        w("  (id, subject_id, subject_type, primary_place_id, tenant_id, workspace_id,")
        w("   display_name, created_at, updated_at)")
        w("VALUES (")
        w(f"  '{prof_id}', '{ind_id}', 'individual', '{place_id}',")
        w(f"  '{TENANT_ID}', '{WORKSPACE_ID}',")
        w(f"  '{display_name.replace(chr(39), chr(39)*2)}', unixepoch(), unixepoch()")
        w(");")

        w("INSERT OR IGNORE INTO politician_profiles")
        w("  (id, profile_id, office_title, jurisdiction_place_id, created_at, updated_at)")
        w("VALUES (")
        w(f"  '{pp_id}', '{prof_id}',")
        w(f"  'Member, Lagos State House of Assembly ({const_inec})',")
        w(f"  '{place_id}', unixepoch(), unixepoch()")
        w(");")

        w("INSERT OR IGNORE INTO political_assignments")
        w("  (id, individual_id, term_id, jurisdiction_place_id, office_type,")
        w("   took_office_year, left_office_year, created_at, updated_at)")
        w("VALUES (")
        w(f"  '{assign_id}', '{ind_id}', '{TERM_LAGOS_ASSEMBLY_ID}',")
        w(f"  '{place_id}', 'state_assembly_member', 2023, NULL, unixepoch(), unixepoch()")
        w(");")

        w("INSERT OR IGNORE INTO party_affiliations")
        w("  (id, individual_id, party_id, start_year, is_current, created_at, updated_at)")
        w("VALUES (")
        w(f"  '{aff_id}', '{ind_id}', '{party_id}', 2023, 1, unixepoch(), unixepoch()")
        w(");")

        w("-- S04 sidecars")
        w("INSERT OR IGNORE INTO seed_dedupe_decisions")
        w("  (id, seed_run_id, entity_type, dedup_key, decision, canonical_id, notes)")
        w("VALUES (")
        w(f"  '{dd_id}', '{SEED_RUN_ID}', 'individual', '{dedup_key}',")
        w(f"  'insert', '{ind_id}',")
        w(f"  'Unique: Lagos {const_inec} seat 2023-2027');")

        w("INSERT OR IGNORE INTO seed_ingestion_records")
        w("  (id, seed_run_id, entity_type, entity_id, source_id, status)")
        w("VALUES (")
        w(f"  '{ir_id}', '{SEED_RUN_ID}', 'individual', '{ind_id}', '{SOURCE_WP_ID}', 'ingested');")

        inec_key = const_inec.lower().replace(" ", "_").replace("/", "_")
        w("INSERT OR IGNORE INTO seed_identity_map")
        w("  (id, seed_run_id, source_id, source_entity_key, canonical_entity_id, entity_type)")
        w("VALUES (")
        w(f"  '{im_id}', '{SEED_RUN_ID}', '{SOURCE_WP_ID}',")
        w(f"  'wp_lagos_assembly_2023_{inec_key}',")
        w(f"  '{ind_id}', 'individual');")

        w("INSERT OR IGNORE INTO seed_place_resolutions")
        w("  (id, seed_run_id, source_name, resolved_place_id, resolution_method, confidence)")
        w("VALUES (")
        w(f"  '{pr_id}', '{SEED_RUN_ID}',")
        w(f"  'Lagos {const_inec}', '{place_id}', 'exact_alias', 1.0);")

        w("INSERT OR IGNORE INTO seed_entity_sources")
        w("  (id, seed_run_id, entity_type, entity_id, source_id, confidence_tier)")
        w("VALUES (")
        w(f"  '{es_id}', '{SEED_RUN_ID}', 'individual', '{ind_id}',")
        w(f"  '{SOURCE_WP_ID}', 'editorial_verified');")

        enr_json = json.dumps({
            "constituency_wp": const_wp,
            "constituency_inec": const_inec,
            "party_abbrev": party_abbr,
            "position": position,
            "source_url": "https://en.wikipedia.org/wiki/List_of_members_of_the_Lagos_State_House_of_Assembly_(2023%E2%80%932027)",
            "resolution_method": m["resolution_method"],
        }).replace("'", "''")
        w("INSERT OR IGNORE INTO seed_enrichment")
        w("  (id, seed_run_id, entity_type, entity_id, enrichment_type, enrichment_json)")
        w("VALUES (")
        w(f"  '{enr_id}', '{SEED_RUN_ID}', 'individual', '{ind_id}',")
        w(f"  'political_assignment', '{enr_json}');")

        kw = f"{display_name} lagos state assembly {const_inec.lower()} {party_abbr.lower()} politician legislator state house"
        anc = f"place_nigeria_001/place_zone_south_west/place_state_lagos/{place_id}"
        w("INSERT OR IGNORE INTO search_entries")
        w("  (id, profile_id, display_name, keywords, ancestry_path, vertical, created_at, updated_at)")
        w("VALUES (")
        w(f"  '{se_id}', '{prof_id}',")
        w(f"  '{display_name.replace(chr(39), chr(39)*2)}',")
        w(f"  '{kw}',")
        w(f"  '{anc}',")
        w("  'politician', unixepoch(), unixepoch()")
        w(");")
        w()

    # ── Search rebuild job ────────────────────────────────────────────────────
    rb_id = stable_id("rb", SEED_RUN_ID)
    w("INSERT OR IGNORE INTO seed_search_rebuild_jobs")
    w("  (id, seed_run_id, status, created_at)")
    w(f"VALUES ('{rb_id}', '{SEED_RUN_ID}', 'pending', unixepoch());")
    w()
    w("-- FTS rebuild")
    w("INSERT OR REPLACE INTO search_fts(search_fts) VALUES ('rebuild');")
    w()
    w("COMMIT;")

    return "\n".join(lines)


def main() -> None:
    data = json.loads(NORMALIZED_PATH.read_text())
    members = data["members"]
    assert len(members) == 40, f"Expected 40 members, got {len(members)}"
    assert data["unresolved"] == [], f"Unresolved: {data['unresolved']}"

    sql = emit_sql(members)

    for path in [MIGRATION_PATH, API_MIGRATION_PATH, SEED_MIRROR_PATH]:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(sql)
        sha = hashlib.sha256(sql.encode()).hexdigest()
        print(f"Written {path} ({len(sql):,} chars, SHA-256: {sha})")

    # Verify all three are byte-identical
    texts = [p.read_text() for p in [MIGRATION_PATH, API_MIGRATION_PATH, SEED_MIRROR_PATH]]
    assert texts[0] == texts[1] == texts[2], "Files are NOT identical!"
    print("All three copies are byte-identical.")


if __name__ == "__main__":
    main()
