import type { PharmacyChainProfile, CreatePharmacyChainInput, PharmacyChainFSMState, DrugInventoryItem, PrescriptionDispensing, DrugSale } from './types.js';
interface D1Like { prepare(s: string): { bind(...v: unknown[]): { run(): Promise<{ success: boolean }>; first<T>(): Promise<T | null>; all<T>(): Promise<{ results: T[] }>; }; }; }
function toProfile(r: Record<string, unknown>): PharmacyChainProfile { return { id: r['id'] as string, workspaceId: r['workspace_id'] as string, tenantId: r['tenant_id'] as string, businessName: r['business_name'] as string, pcnLicence: r['pcn_licence'] as string|null, nafdacLicence: r['nafdac_licence'] as string|null, cacRc: r['cac_rc'] as string|null, category: r['category'] as PharmacyChainProfile['category'], status: r['status'] as PharmacyChainFSMState, createdAt: r['created_at'] as number, updatedAt: r['updated_at'] as number }; }
function toDrug(r: Record<string, unknown>): DrugInventoryItem { return { id: r['id'] as string, profileId: r['profile_id'] as string, tenantId: r['tenant_id'] as string, drugName: r['drug_name'] as string, nafdacReg: r['nafdac_reg'] as string|null, quantityInStock: r['quantity_in_stock'] as number, reorderLevel: r['reorder_level'] as number, unitPriceKobo: r['unit_price_kobo'] as number, wholesalePriceKobo: r['wholesale_price_kobo'] as number, expiryDate: r['expiry_date'] as number|null, prescriptionRequired: Boolean(r['prescription_required']), createdAt: r['created_at'] as number, updatedAt: r['updated_at'] as number }; }
export class PharmacyChainRepository {
  constructor(private readonly db: D1Like) {}
  async createProfile(input: CreatePharmacyChainInput): Promise<PharmacyChainProfile> {
    const id = input.id ?? crypto.randomUUID();
    await this.db.prepare(`INSERT INTO pharmacy_chain_profiles (id,workspace_id,tenant_id,business_name,pcn_licence,nafdac_licence,cac_rc,category,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,'seeded',unixepoch(),unixepoch())`).bind(id,input.workspaceId,input.tenantId,input.businessName,input.pcnLicence??null,input.nafdacLicence??null,input.cacRc??null,input.category??'retail').run();
    const p = await this.findProfileById(id, input.tenantId); if (!p) throw new Error('[pharmacy-chain] create failed'); return p;
  }
  async findProfileById(id: string, tenantId: string): Promise<PharmacyChainProfile|null> { const r = await this.db.prepare('SELECT * FROM pharmacy_chain_profiles WHERE id=? AND tenant_id=?').bind(id,tenantId).first<Record<string,unknown>>(); return r ? toProfile(r) : null; }
  async findProfileByWorkspace(workspaceId: string, tenantId: string): Promise<PharmacyChainProfile|null> { const r = await this.db.prepare('SELECT * FROM pharmacy_chain_profiles WHERE workspace_id=? AND tenant_id=?').bind(workspaceId,tenantId).first<Record<string,unknown>>(); return r ? toProfile(r) : null; }
  async transitionStatus(id: string, tenantId: string, to: PharmacyChainFSMState, fields?: { pcnLicence?: string; nafdacLicence?: string }): Promise<PharmacyChainProfile> {
    const extraClauses: string[] = []; const extraBinds: unknown[] = [];
    if (fields?.pcnLicence) { extraClauses.push('pcn_licence = ?'); extraBinds.push(fields.pcnLicence); }
    if (fields?.nafdacLicence) { extraClauses.push('nafdac_licence = ?'); extraBinds.push(fields.nafdacLicence); }
    await this.db.prepare(`UPDATE pharmacy_chain_profiles SET status=?${extraClauses.length ? ', ' + extraClauses.join(', ') : ''}, updated_at=unixepoch() WHERE id=? AND tenant_id=?`).bind(to,...extraBinds,id,tenantId).run();
    const p = await this.findProfileById(id, tenantId); if (!p) throw new Error('[pharmacy-chain] not found'); return p;
  }
  async addDrugInventory(profileId: string, tenantId: string, input: { drugName: string; nafdacReg?: string; quantityInStock: number; reorderLevel?: number; unitPriceKobo: number; wholesalePriceKobo?: number; expiryDate?: number; prescriptionRequired?: boolean }): Promise<DrugInventoryItem> {
    if (!Number.isInteger(input.unitPriceKobo)) throw new Error('unit_price_kobo must be integer (P9)');
    const id = crypto.randomUUID();
    await this.db.prepare('INSERT INTO drug_inventory (id,profile_id,tenant_id,drug_name,nafdac_reg,quantity_in_stock,reorder_level,unit_price_kobo,wholesale_price_kobo,expiry_date,prescription_required,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,unixepoch(),unixepoch())').bind(id,profileId,tenantId,input.drugName,input.nafdacReg??null,input.quantityInStock,input.reorderLevel??10,input.unitPriceKobo,input.wholesalePriceKobo??0,input.expiryDate??null,input.prescriptionRequired?1:0).run();
    const r = await this.db.prepare('SELECT * FROM drug_inventory WHERE id=? AND tenant_id=?').bind(id,tenantId).first<Record<string,unknown>>(); if (!r) throw new Error('[pharmacy-chain] drug create failed'); return toDrug(r);
  }
  async listDrugInventory(profileId: string, tenantId: string): Promise<DrugInventoryItem[]> { const { results } = await this.db.prepare('SELECT * FROM drug_inventory WHERE profile_id=? AND tenant_id=?').bind(profileId,tenantId).all<Record<string,unknown>>(); return results.map(toDrug); }
  async dispensePrescription(profileId: string, tenantId: string, input: { patientRefId: string; prescriberRefId?: string; drugId: string; quantity: number; totalKobo: number; dispensedDate: number }): Promise<PrescriptionDispensing> {
    if (!Number.isInteger(input.totalKobo)) throw new Error('total_kobo must be integer (P9)');
    const id = crypto.randomUUID();
    await this.db.prepare('INSERT INTO prescription_dispensing (id,profile_id,tenant_id,patient_ref_id,prescriber_ref_id,drug_id,quantity,total_kobo,dispensed_date,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,\'pending\',unixepoch())').bind(id,profileId,tenantId,input.patientRefId,input.prescriberRefId??null,input.drugId,input.quantity,input.totalKobo,input.dispensedDate).run();
    const r = await this.db.prepare('SELECT * FROM prescription_dispensing WHERE id=? AND tenant_id=?').bind(id,tenantId).first<Record<string,unknown>>(); if (!r) throw new Error('[pharmacy-chain] dispensing create failed');
    return { id: r['id'] as string, profileId: r['profile_id'] as string, tenantId: r['tenant_id'] as string, patientRefId: r['patient_ref_id'] as string, prescriberRefId: r['prescriber_ref_id'] as string|null, drugId: r['drug_id'] as string, quantity: r['quantity'] as number, totalKobo: r['total_kobo'] as number, dispensedDate: r['dispensed_date'] as number, status: r['status'] as string, createdAt: r['created_at'] as number };
  }
  async recordSale(profileId: string, tenantId: string, input: { drugId: string; clientRefId?: string; quantity: number; unitPriceKobo: number; totalKobo: number; saleDate: number; isPrescription?: boolean; isWholesale?: boolean }): Promise<DrugSale> {
    if (!Number.isInteger(input.totalKobo)) throw new Error('total_kobo must be integer (P9)');
    const id = crypto.randomUUID();
    await this.db.prepare('INSERT INTO drug_sales (id,profile_id,tenant_id,drug_id,client_ref_id,quantity,unit_price_kobo,total_kobo,sale_date,is_prescription,is_wholesale,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,unixepoch())').bind(id,profileId,tenantId,input.drugId,input.clientRefId??null,input.quantity,input.unitPriceKobo,input.totalKobo,input.saleDate,input.isPrescription?1:0,input.isWholesale?1:0).run();
    const r = await this.db.prepare('SELECT * FROM drug_sales WHERE id=? AND tenant_id=?').bind(id,tenantId).first<Record<string,unknown>>(); if (!r) throw new Error('[pharmacy-chain] sale create failed');
    return { id: r['id'] as string, profileId: r['profile_id'] as string, tenantId: r['tenant_id'] as string, drugId: r['drug_id'] as string, clientRefId: r['client_ref_id'] as string|null, quantity: r['quantity'] as number, unitPriceKobo: r['unit_price_kobo'] as number, totalKobo: r['total_kobo'] as number, saleDate: r['sale_date'] as number, isPrescription: Boolean(r['is_prescription']), isWholesale: Boolean(r['is_wholesale']), createdAt: r['created_at'] as number };
  }
  async listSales(profileId: string, tenantId: string): Promise<DrugSale[]> { const { results } = await this.db.prepare('SELECT * FROM drug_sales WHERE profile_id=? AND tenant_id=? ORDER BY sale_date DESC').bind(profileId,tenantId).all<Record<string,unknown>>(); return results.map(r => ({ id: r['id'] as string, profileId: r['profile_id'] as string, tenantId: r['tenant_id'] as string, drugId: r['drug_id'] as string, clientRefId: r['client_ref_id'] as string|null, quantity: r['quantity'] as number, unitPriceKobo: r['unit_price_kobo'] as number, totalKobo: r['total_kobo'] as number, saleDate: r['sale_date'] as number, isPrescription: Boolean(r['is_prescription']), isWholesale: Boolean(r['is_wholesale']), createdAt: r['created_at'] as number })); }
}
export function guardSeedToClaimed(_p: PharmacyChainProfile): { allowed: boolean; reason?: string } { return { allowed: true }; }
