-- WebWaka OS QA Seed — Phase 8: USSD Sessions
-- Source: WebWaka_OS_QA_Execution_Plan.md v1.0 §3.1 Phase 8
-- Frozen baseline: WebWaka_OS_Corrected_Master_Inventory_v2.0-FROZEN
--
-- SCHEMA NOTE 2026-04-23: No ussd_session_audit table exists in D1 migrations.
-- USSD sessions are entirely KV-based (stored in USSD_SESSION_KV namespace).
-- SQL D1 inserts are NOT applicable for USSD session state.
-- The INSERT OR IGNORE statements from the original seed have been removed to
-- prevent seed failures. KV seed commands are documented below for manual
-- execution during QA test setup.
--
-- T10: Each USSD Worker is scoped to a single tenant (TENANT_ID in wrangler.toml).
--      Sessions are stored in USSD_SESSION_KV (KV namespace binding).
--      USSD session KV key format: ussd_session:{sessionId}
--
-- R5: Rate limit is 30 USSD requests per phone number per hour.
--     TC-US010 exhausts the rate limit for +2348000000020 (USSD-002 phone).
--     After that test, flush KV: wrangler kv:key delete ussd_rl:+2348000000020

-- ─────────────────────────────────────────────────────────────────
-- KV seed commands (run separately against ussd-staging namespace):
--
-- USSD-001: Active session for USR-009 (+2348000000009), main_menu state
-- wrangler kv:key put --namespace-id=<USSD_SESSION_KV_ID> \
--   "ussd_session:qa-session-001" \
--   '{"state":"main_menu","phone":"+2348000000009",
--     "tenant_id":"10000000-0000-4000-b000-000000000001","step":0}' \
--   --ttl=120 --env staging
--
-- USSD-003: Expired session (TTL=1 to immediately expire)
-- wrangler kv:key put --namespace-id=<USSD_SESSION_KV_ID> \
--   "ussd_session:qa-session-003" \
--   '{"state":"main_menu","phone":"+2348000000021",
--     "tenant_id":"10000000-0000-4000-b000-000000000001","step":0}' \
--   --ttl=1 --env staging
-- ─────────────────────────────────────────────────────────────────

-- No SQL statements: USSD state lives entirely in KV, not D1.
-- This file intentionally left without INSERT statements.
SELECT 1; -- no-op to satisfy wrangler d1 execute (requires at least one statement)
