#!/usr/bin/env node
/**
 * generate-vertical.ts — Wave 3 B4-5
 * WebWaka OS — Scaffolds a new VerticalConfig entry from CLI args.
 *
 * Usage:
 *   pnpm run generate:vertical <slug> [--pillar 1|2|3] [--milestone M9] [--maturity full|basic|stub]
 *
 * What it does:
 *   1. Validates the slug (lowercase, hyphens, no spaces)
 *   2. Generates a VerticalConfig block with the provided params
 *   3. Prints it to stdout (ready to paste into registry.ts)
 *   4. Optionally writes a migration stub to apps/api/migrations/
 */

import * as path from 'path';
import * as fs from 'fs';

// ── CLI arg parsing ───────────────────────────────────────────────────────────
const args = process.argv.slice(2);
const slug = args[0];

if (!slug || slug.startsWith('--')) {
  console.error('Usage: generate-vertical <slug> [--pillar 1|2|3] [--milestone M9] [--maturity full|basic|stub]');
  process.exit(1);
}

if (!/^[a-z][a-z0-9-]+$/.test(slug)) {
  console.error(`Invalid slug "${slug}". Must be lowercase letters, digits, and hyphens only.`);
  process.exit(1);
}

function getFlag(name: string, defaultVal: string): string {
  const idx = args.indexOf(`--${name}`);
  return idx !== -1 && args[idx + 1] ? args[idx + 1]! : defaultVal;
}

const pillar   = parseInt(getFlag('pillar', '1'), 10) as 1 | 2 | 3;
const milestone = getFlag('milestone', 'M9');
const maturity  = getFlag('maturity', 'stub') as 'full' | 'basic' | 'stub';

if (![1, 2, 3].includes(pillar)) {
  console.error('--pillar must be 1, 2, or 3');
  process.exit(1);
}

if (!['full', 'basic', 'stub'].includes(maturity)) {
  console.error('--maturity must be full, basic, or stub');
  process.exit(1);
}

// ── Derivations ───────────────────────────────────────────────────────────────
const tableName   = slug.replace(/-/g, '_') + '_profiles';
const propPrefix  = slug.split('-').map((w, i) => i === 0 ? w : w[0]!.toUpperCase() + w.slice(1)).join('');
const displayName = slug.split('-').map(w => w[0]!.toUpperCase() + w.slice(1)).join(' ');
const entLayerMap: Record<number, string> = { 1: 'Commerce', 2: 'Civic', 3: 'Government' };
const entitlementLayer = entLayerMap[pillar]!;

// ── Config block ──────────────────────────────────────────────────────────────
const configBlock = `
  '${slug}': {
    slug: '${slug}',
    displayName: '${displayName}',
    primaryPillar: ${pillar},
    milestone: '${milestone}',
    maturity: '${maturity}',
    tableName: '${tableName}',
    entityType: 'organization',
    profileFields: [
      { column: 'business_name', property: 'businessName', type: 'string', required: true, label: 'Business Name' },
      { column: 'cac_number', property: 'cacNumber', type: 'string', nullable: true, label: 'CAC Number' },
    ],
    createFields: ['businessName'],
    updateFields: ['businessName', 'cacNumber'],
    fsm: {
      states: ['seeded', 'claimed', 'active', 'suspended'],
      initialState: 'seeded',
      transitions: [
        { from: 'seeded', to: 'claimed' },
        { from: 'claimed', to: 'active' },
        { from: 'active', to: 'suspended' },
        { from: 'suspended', to: 'active' },
      ],
    },
    subEntities: [],
    ai: {
      autonomyLevel: 1,
      allowedCapabilities: ['bio_generator'],
      useCases: ['Generate ${displayName} profile bio'],
    },
    route: { basePath: '/${slug}', entitlementLayer: '${entitlementLayer}' },
    compliance: { kycTierForClaim: 1, ndprLevel: 'standard' },
  },
`;

// ── Migration stub ────────────────────────────────────────────────────────────
const ROOT = path.resolve(__dirname, '..');
const migrationsDir = path.join(ROOT, 'apps/api/migrations');
let migrationPath = '';

if (fs.existsSync(migrationsDir)) {
  const existing = fs.readdirSync(migrationsDir).filter(f => /^\d+/.test(f));
  const nextNum = String(
    Math.max(0, ...existing.map(f => parseInt(f.split('_')[0]!, 10))) + 1,
  ).padStart(4, '0');
  migrationPath = path.join(migrationsDir, `${nextNum}_vertical_${slug.replace(/-/g, '_')}.sql`);
  const migrationSql = `-- Auto-generated by generate-vertical for '${slug}'
-- Wave 3 B4-5: ${new Date().toISOString().split('T')[0]}
CREATE TABLE IF NOT EXISTS ${tableName} (
  id            TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(8)))),
  workspace_id  TEXT NOT NULL,
  tenant_id     TEXT NOT NULL,
  business_name TEXT NOT NULL,
  cac_number    TEXT,
  state         TEXT NOT NULL DEFAULT 'seeded',
  created_at    INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at    INTEGER NOT NULL DEFAULT (unixepoch()),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_${slug.replace(/-/g, '_')}_workspace ON ${tableName}(workspace_id);
CREATE INDEX IF NOT EXISTS idx_${slug.replace(/-/g, '_')}_tenant   ON ${tableName}(tenant_id);
`;
  fs.writeFileSync(migrationPath, migrationSql);
  console.error(`✅  Migration stub written: ${path.relative(ROOT, migrationPath)}`);
}

// ── Output ────────────────────────────────────────────────────────────────────
console.log('');
console.log('// ── Paste this into REGISTRY in packages/vertical-engine/src/registry.ts ──');
console.log(configBlock);
console.log('');
console.log('// Next steps:');
console.log(`//   1. Search for '${slug}' in registry.ts to confirm it is not already present`);
console.log('//   2. Paste the block above before the REGISTRY closing `};`');
console.log('//   3. Fill in all TODOs (profileFields, FSM states, compliance)');
console.log(`//   4. Run: pnpm vitest run packages/vertical-engine/src/registry.test.ts`);
if (migrationPath) {
  console.log(`//   5. Review and adjust the migration: ${path.relative(ROOT, migrationPath)}`);
}
