-- Rollback for ALTER TABLE migration
-- SQLite <3.35 does not support DROP COLUMN. Manual table rebuild required.
-- ALTER TABLE contact_channels DROP COLUMN telegram_chat_id; -- D1/SQLite does not support DROP COLUMN before 3.35
