-- Migration 0464: P3 Website Templates — Seed All 78 Niche Templates into template_registry
-- Phase 2 Completion Sprint (May 2026)
--
-- Seeds all 78 P3-tier website templates (71 IMPLEMENTED + 7 P3-SHIPPED-via-P2-sprint)
-- into template_registry so they are discoverable in the template marketplace.
--
-- Background:
--   All WebsiteTemplateContract TypeScript files exist in apps/brand-runtime/src/templates/niches/
--   All are registered in BUILT_IN_TEMPLATES in template-resolver.ts.
--   The existing SQL seed files in infra/db/seeds/templates/ target a `website_templates` table
--   (PostgreSQL ARRAY syntax) which does not exist in D1. This migration creates D1-compatible
--   INSERT OR IGNORE rows in `template_registry` (migration 0206) instead.
--
-- Platform Invariants:
--   T3  — author_tenant_id=NULL means platform-authored (no tenant scope)
--   T2  — no ARRAY literals, no NOW(), no RETURNING — D1/SQLite only
--   AC-FUNC-03 — rollback in rollback/0464_rollback.sql
--
-- Note: INSERT OR IGNORE — safe to re-run; idempotent.

INSERT OR IGNORE INTO template_registry
  (id, slug, display_name, description, template_type, version, platform_compat,
   compatible_verticals, manifest_json, author_tenant_id, status,
   is_free, price_kobo, install_count, tags,
   module_config, vocabulary, default_policies, default_workflows,
   created_at, updated_at)
VALUES
(
  'tpl_p3_mosque_mosque_community_platform_v100',
  'mosque-mosque-community-platform',
  'Mosque / Islamic Centre',
  'Community platform for mosques: Jumu''ah scheduling, zakat management, madrassa enrolment, and community announcements.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["mosque"]',
  '{"name": "mosque-mosque-community-platform", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "mosque", "category": "civic"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["civic", "faith", "islamic", "mosque", "nigeria-first", "zakat"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_youth_organization_youth_org_portal_v100',
  'youth-organization-youth-org-portal',
  'Youth Organisation / Student Union',
  'Digital platform for youth bodies and student unions: membership, events, elections, and NYSC coordination.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["youth-organization"]',
  '{"name": "youth-organization-youth-org-portal", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "youth-organization", "category": "civic"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["civic", "community", "nigeria-first", "student-union", "youth"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_womens_association_womens_assoc_portal_v100',
  'womens-association-womens-assoc-portal',
  'Women''s Association / Forum',
  'Community portal for women''s associations and forums: membership, cooperative savings, advocacy, and events.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["womens-association"]',
  '{"name": "womens-association-womens-assoc-portal", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "womens-association", "category": "civic"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["association", "civic", "cooperative", "nigeria-first", "women"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_professional_association_prof_assoc_port_v100',
  'professional-association-prof-assoc-portal',
  'Professional Association',
  'Portal for professional associations (NBA, NMA, ICAN): member directory, CPD tracking, events, and regulatory news.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["professional-association"]',
  '{"name": "professional-association-prof-assoc-portal", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "professional-association", "category": "civic"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["association", "nba", "nigeria-first", "nma", "professional"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_orphanage_orphanage_welfare_portal_v100',
  'orphanage-orphanage-welfare-portal',
  'Orphanage / Child Welfare NGO',
  'Welfare portal for orphanages and child care NGOs: donation management, child welfare reporting, and donor transparency.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["orphanage"]',
  '{"name": "orphanage-orphanage-welfare-portal", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "orphanage", "category": "civic"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["children", "ngo", "nigeria-first", "orphanage", "welfare"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_sports_club_sports_club_portal_v100',
  'sports-club-sports-club-portal',
  'Sports Club / Amateur League',
  'Club portal for amateur sports clubs and local football leagues: fixtures, standings, player profiles, and membership.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["sports-club"]',
  '{"name": "sports-club-sports-club-portal", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "sports-club", "category": "civic"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["club", "football", "leisure", "nigeria-first", "sports"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_book_club_book_club_platform_v100',
  'book-club-book-club-platform',
  'Book Club / Reading Circle',
  'Reading community platform: monthly picks, discussion forums, event scheduling, and African literature focus.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["book-club"]',
  '{"name": "book-club-book-club-platform", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "book-club", "category": "civic"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["book-club", "community", "literary", "nigeria-first", "reading"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_market_association_market_assoc_portal_v100',
  'market-association-market-assoc-portal',
  'Market Leaders / Traders Association',
  'Association portal for market leaders and traders unions: member directory, dues collection, notices, and market governance.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["market-association"]',
  '{"name": "market-association-market-assoc-portal", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "market-association", "category": "civic"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["association", "commerce", "market", "nigeria-first", "traders"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_ministry_mission_ministry_mission_platfo_v100',
  'ministry-mission-ministry-mission-platform',
  'Ministry / Apostolic Mission',
  'Platform for ministries and apostolic missions: outreach programmes, sermon archive, tithes, and volunteer coordination.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["ministry-mission"]',
  '{"name": "ministry-mission-ministry-mission-platform", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "ministry-mission", "category": "civic"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["faith", "ministry", "mission", "nigeria-first", "outreach"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_campaign_office_campaign_office_ops_v100',
  'campaign-office-campaign-office-ops',
  'Political Campaign Office',
  'Campaign operations site: volunteer sign-up, GOTV tracking, donation pages, and ward-level mobilisation.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["campaign-office"]',
  '{"name": "campaign-office-campaign-office-ops", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "campaign-office", "category": "politics"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["campaign", "election", "gotv", "nigeria-first", "politics"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_lga_office_lga_council_portal_v100',
  'lga-office-lga-council-portal',
  'Local Government Council / Ward Office',
  'LGA council transparency portal: councillor directory, council minutes, project tracker, and citizen contact.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["lga-office"]',
  '{"name": "lga-office-lga-council-portal", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "lga-office", "category": "politics"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["council", "government", "lga", "nigeria-first", "transparency"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_polling_unit_rep_polling_unit_rep_site_v100',
  'polling-unit-rep-polling-unit-rep-site',
  'Polling Unit Representative',
  'Information site for polling unit representatives and ward coordinators: voter education and contact details.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["polling-unit"]',
  '{"name": "polling-unit-rep-polling-unit-rep-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "polling-unit", "category": "politics"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["election", "inec", "nigeria-first", "polling-unit", "voter-education"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_constituency_office_constituency_dev_por_v100',
  'constituency-office-constituency-dev-portal',
  'Constituency Development Office',
  'Constituency portal: development fund tracker, project listing, constituent contact, and representative profile.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["constituency-office"]',
  '{"name": "constituency-office-constituency-dev-portal", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "constituency-office", "category": "politics"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["constituency", "development", "government", "nigeria-first", "transparency"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_okada_keke_okada_keke_coop_v100',
  'okada-keke-okada-keke-coop',
  'Okada / Keke Rider Co-op',
  'Cooperative platform for okada and keke riders: member registration, dues, route management, and insurance coordination.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["okada-keke"]',
  '{"name": "okada-keke-okada-keke-coop", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "okada-keke", "category": "transport"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["cooperative", "keke", "nigeria-first", "okada", "transport"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_ferry_ferry_water_transport_v100',
  'ferry-ferry-water-transport',
  'Ferry / Water Transport Operator',
  'Water transport booking and schedule site for ferry operators: routes, fares, safety records, and online booking.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["ferry"]',
  '{"name": "ferry-ferry-water-transport", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "ferry", "category": "transport"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["boat", "ferry", "lagos", "nigeria-first", "water-transport"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_airport_shuttle_airport_shuttle_booking_v100',
  'airport-shuttle-airport-shuttle-booking',
  'Airport Shuttle Service',
  'Airport transfer booking site: pre-book rides, compare rates, track driver, and manage corporate accounts.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["airport-shuttle"]',
  '{"name": "airport-shuttle-airport-shuttle-booking", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "airport-shuttle", "category": "transport"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["airport", "booking", "nigeria-first", "shuttle", "transport"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_container_depot_container_depot_hub_v100',
  'container-depot-container-depot-hub',
  'Container Depot / Logistics Hub',
  'Inland container depot operations: slot booking, demurrage tracking, haulage coordination, and customs liaison.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["container-depot"]',
  '{"name": "container-depot-container-depot-hub", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "container-depot", "category": "transport"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["container", "depot", "logistics", "nigeria-first", "shipping"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_cargo_truck_cargo_fleet_ops_v100',
  'cargo-truck-cargo-fleet-ops',
  'Cargo Truck / Fleet Operator',
  'Fleet management site for cargo truck operators: load matching, trip tracking, driver profiles, and maintenance logs.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["cargo-truck"]',
  '{"name": "cargo-truck-cargo-fleet-ops", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "cargo-truck", "category": "transport"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["cargo", "fleet", "haulage", "nigeria-first", "truck"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_airtime_reseller_airtime_vtu_reseller_v100',
  'airtime-reseller-airtime-vtu-reseller',
  'Airtime / VTU Reseller',
  'Service site for airtime and VTU resellers: top-up services, data bundles, utility bills, and agent sign-up.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["airtime-reseller"]',
  '{"name": "airtime-reseller-airtime-vtu-reseller", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "airtime-reseller", "category": "financial"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["airtime", "fintech", "mobile", "nigeria-first", "vtu"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_used_car_dealer_used_car_dealer_site_v100',
  'used-car-dealer-used-car-dealer-site',
  'Used Car Dealer / Auto Trader',
  'Showroom site for used car dealers: vehicle listings, specifications, WhatsApp inquiry, and inspection reports.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["used-car-dealer"]',
  '{"name": "used-car-dealer-used-car-dealer-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "used-car-dealer", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["automotive", "cars", "dealer", "nigeria-first", "used-car"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_spare_parts_spare_parts_dealer_v100',
  'spare-parts-spare-parts-dealer',
  'Spare Parts Dealer (Ladipo / Nnewi)',
  'Spare parts shop site: parts catalogue, brand compatibility, bulk pricing, and Ladipo/Nnewi market presence.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["spare-parts"]',
  '{"name": "spare-parts-spare-parts-dealer", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "spare-parts", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["automotive", "ladipo", "nigeria-first", "nnewi", "spare-parts"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_tyre_shop_tyre_shop_service_v100',
  'tyre-shop-tyre-shop-service',
  'Tyre Shop / Vulcanizer',
  'Tyre and vulcanizing shop site: brand listing, fitting services, WhatsApp booking, and roadside assistance.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["tyre-shop"]',
  '{"name": "tyre-shop-tyre-shop-service", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "tyre-shop", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["automotive", "nigeria-first", "repair", "tyre", "vulcanizer"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_car_wash_car_wash_detailing_v100',
  'car-wash-car-wash-detailing',
  'Car Wash / Auto Detailing',
  'Car wash and detailing service site: packages, pricing, booking, and mobile detailing options.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["car-wash"]',
  '{"name": "car-wash-car-wash-detailing", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "car-wash", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["automotive", "car-wash", "cleaning", "detailing", "nigeria-first"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_motorcycle_accessories_moto_accessories__v100',
  'motorcycle-accessories-moto-accessories-shop',
  'Motorcycle Accessories Shop',
  'Motorcycle accessories retail site: helmets, spare parts, riding gear, and okada/dispatch supply catalogue.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["motorcycle-accessories"]',
  '{"name": "motorcycle-accessories-moto-accessories-shop", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "motorcycle-accessories", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["accessories", "motorcycle", "nigeria-first", "retail", "spare-parts"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_building_materials_building_materials_su_v100',
  'building-materials-building-materials-supplier',
  'Building Materials Supplier',
  'Building materials supplier site: product catalogue, bulk pricing, delivery zones, and site-supply options.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["building-materials"]',
  '{"name": "building-materials-building-materials-supplier", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "building-materials", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["building-materials", "construction", "hardware", "nigeria-first", "retail"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_iron_steel_iron_steel_merchant_v100',
  'iron-steel-iron-steel-merchant',
  'Iron & Steel / Roofing Merchant',
  'Iron rods, roofing sheets, and steel merchant site: product specs, tonnage pricing, and delivery nationwide.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["iron-steel"]',
  '{"name": "iron-steel-iron-steel-merchant", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "iron-steel", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["construction", "iron", "nigeria-first", "roofing", "steel"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_electrical_fittings_electrical_fittings__v100',
  'electrical-fittings-electrical-fittings-dealer',
  'Electrical Fittings Dealer',
  'Electrical fittings and supplies dealer site: product catalogue, bulk order pricing, and contractor accounts.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["electrical-fittings"]',
  '{"name": "electrical-fittings-electrical-fittings-dealer", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "electrical-fittings", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["electrical", "fittings", "hardware", "nigeria-first", "wholesale"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_paints_distributor_paints_distributor_si_v100',
  'paints-distributor-paints-distributor-site',
  'Paints & Coatings Distributor',
  'Paints distributor site: brand stockist, colour range, trade pricing, and applicator training events.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["paints-distributor"]',
  '{"name": "paints-distributor-paints-distributor-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "paints-distributor", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["coatings", "construction", "distribution", "nigeria-first", "paints"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_plumbing_supplies_plumbing_supplies_deal_v100',
  'plumbing-supplies-plumbing-supplies-dealer',
  'Plumbing Supplies Dealer',
  'Plumbing supplies dealer site: pipes, fittings, water tanks, and bulk contractor pricing.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["plumbing-supplies"]',
  '{"name": "plumbing-supplies-plumbing-supplies-dealer", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "plumbing-supplies", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["construction", "hardware", "nigeria-first", "plumbing", "supplies"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_generator_dealer_generator_dealer_servic_v100',
  'generator-dealer-generator-dealer-service',
  'Generator Sales & Service Centre',
  'Generator sales and service site: brand stockist, power sizing guide, maintenance contracts, and spare parts.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["generator-dealer"]',
  '{"name": "generator-dealer-generator-dealer-service", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "generator-dealer", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["generator", "nigeria-first", "power", "sales", "service"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_internet_cafe_internet_cafe_business_cen_v100',
  'internet-cafe-internet-cafe-business-centre',
  'Internet Café / Business Centre',
  'Internet café and business centre site: services, pricing, printing, scanning, and office services.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["internet-cafe"]',
  '{"name": "internet-cafe-internet-cafe-business-centre", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "internet-cafe", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["business-centre", "internet-cafe", "nigeria-first", "printing", "services"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_printing_press_printing_press_studio_v100',
  'printing-press-printing-press-studio',
  'Printing Press / Design Studio',
  'Commercial printing and design studio site: offset, digital printing, branding, and bulk order quotes.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["printing-press"]',
  '{"name": "printing-press-printing-press-studio", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "printing-press", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["branding", "design", "nigeria-first", "press", "printing"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_laundry_service_laundry_service_site_v100',
  'laundry-service-laundry-service-site',
  'Laundromat / Laundry Service',
  'Laundry and dry cleaning service site: package pricing, pickup/delivery, item tracking, and subscription plans.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["laundry-service"]',
  '{"name": "laundry-service-laundry-service-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "laundry-service", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["dry-cleaning", "household", "laundry", "nigeria-first", "services"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_hair_salon_hair_salon_site_v100',
  'hair-salon-hair-salon-site',
  'Hair Salon / Barbing Salon',
  'Hair salon and barbing shop site: service menu, pricing, stylist profiles, and WhatsApp appointment booking.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["hair-salon"]',
  '{"name": "hair-salon-hair-salon-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "hair-salon", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["barbing", "beauty", "hair-salon", "nigeria-first", "personal-care"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_cleaning_company_cleaning_facility_mgmt_v100',
  'cleaning-company-cleaning-facility-mgmt',
  'Cleaning & Facility Management Company',
  'Commercial cleaning and facility management company site: services, coverage areas, corporate contracts, and quote request.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["cleaning-company"]',
  '{"name": "cleaning-company-cleaning-facility-mgmt", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "cleaning-company", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["cleaning", "corporate", "facility-management", "nigeria-first", "services"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_shoemaker_shoemaker_atelier_v100',
  'shoemaker-shoemaker-atelier',
  'Shoe Cobbler / Shoe Maker Atelier',
  'Bespoke shoe making and cobbling atelier site: portfolio, custom orders, repair services, and material options.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["shoemaker"]',
  '{"name": "shoemaker-shoemaker-atelier", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "shoemaker", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["cobbler", "crafts", "leather", "nigeria-first", "shoemaker"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_tailoring_fashion_tailoring_atelier_v100',
  'tailoring-fashion-tailoring-atelier',
  'Tailor / Fashion Designer Atelier',
  'Tailoring and fashion design atelier site: portfolio, style gallery, measurement guide, and WhatsApp order.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["tailoring-fashion"]',
  '{"name": "tailoring-fashion-tailoring-atelier", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "tailoring-fashion", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["atelier", "bespoke", "fashion", "nigeria-first", "tailoring"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_phone_repair_shop_phone_repair_shop_v100',
  'phone-repair-shop-phone-repair-shop',
  'Phone Repair & Accessories Shop',
  'Phone repair shop site: device support list, repair pricing, accessories catalogue, and booking.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["phone-repair-shop"]',
  '{"name": "phone-repair-shop-phone-repair-shop", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "phone-repair-shop", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["accessories", "electronics", "nigeria-first", "phone-repair", "services"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_water_vendor_water_vendor_site_v100',
  'water-vendor-water-vendor-site',
  'Water Tanker / Sachet Water Producer',
  'Water vendor site: tanker delivery booking, sachet water orders, coverage areas, and bulk pricing.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["water-vendor"]',
  '{"name": "water-vendor-water-vendor-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "water-vendor", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["nigeria-first", "sachet", "tanker", "vendor", "water"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_oil_gas_services_oil_gas_service_provide_v100',
  'oil-gas-services-oil-gas-service-provider',
  'Oil & Gas Service Provider',
  'Oil and gas field services company site: service catalogue, DPR licensing, project portfolio, and tender register.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["oil-gas-services"]',
  '{"name": "oil-gas-services-oil-gas-service-provider", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "oil-gas-services", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["dpr", "energy", "nigeria-first", "oil-gas", "services"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_borehole_driller_borehole_drilling_v100',
  'borehole-driller-borehole-drilling',
  'Borehole Drilling Company',
  'Borehole drilling company site: service zones, rig capacity, water table reports, and project portfolio.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["borehole-driller"]',
  '{"name": "borehole-driller-borehole-drilling", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "borehole-driller", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["borehole", "construction", "drilling", "nigeria-first", "water"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_artisanal_mining_artisanal_mining_ops_v100',
  'artisanal-mining-artisanal-mining-ops',
  'Artisanal Mining Operator',
  'Artisanal mining operations site: mine profiles, mineral types, cooperative structure, and regulatory compliance.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["artisanal-mining"]',
  '{"name": "artisanal-mining-artisanal-mining-ops", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "artisanal-mining", "category": "commerce"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["artisanal", "extraction", "minerals", "mining", "nigeria-first"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_poultry_farm_poultry_farm_site_v100',
  'poultry-farm-poultry-farm-site',
  'Poultry Farm / Aquaculture',
  'Poultry farm and fish pond site: production capacity, product availability, bulk orders, and farm visits.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["poultry-farm"]',
  '{"name": "poultry-farm-poultry-farm-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "poultry-farm", "category": "agricultural"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["agric", "aquaculture", "farm", "nigeria-first", "poultry"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_cassava_miller_cassava_miller_site_v100',
  'cassava-miller-cassava-miller-site',
  'Cassava / Maize / Rice Miller',
  'Cassava, maize, and rice miller site: milling capacity, product types (garri, flour), bulk pricing, and delivery.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["cassava-miller"]',
  '{"name": "cassava-miller-cassava-miller-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "cassava-miller", "category": "agricultural"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["agri-processing", "cassava", "garri", "miller", "nigeria-first"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_fish_market_fish_market_site_v100',
  'fish-market-fish-market-site',
  'Fish Market / Fishmonger',
  'Fish market and fishmonger site: fish types, pricing, freshness guarantee, bulk orders, and market location.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["fish-market"]',
  '{"name": "fish-market-fish-market-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "fish-market", "category": "agricultural"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["fish", "fishmonger", "fresh", "market", "nigeria-first"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_abattoir_abattoir_meat_processing_v100',
  'abattoir-abattoir-meat-processing',
  'Abattoir / Meat Processing',
  'Abattoir and meat processing site: NAFDAC-certified, species handled, bulk meat orders, and cold chain.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["abattoir"]',
  '{"name": "abattoir-abattoir-meat-processing", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "abattoir", "category": "agricultural"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["abattoir", "halal", "meat", "nigeria-first", "processing"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_produce_aggregator_produce_aggregator_si_v100',
  'produce-aggregator-produce-aggregator-site',
  'Produce Storage / Market Aggregator',
  'Produce aggregation and storage site: commodity types, cold storage capacity, farmer onboarding, and off-taker connections.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["produce-aggregator"]',
  '{"name": "produce-aggregator-produce-aggregator-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "produce-aggregator", "category": "agricultural"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["aggregator", "agric", "nigeria-first", "produce", "storage"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_vegetable_garden_urban_veg_garden_v100',
  'vegetable-garden-urban-veg-garden',
  'Vegetable Garden / Urban Horticulture',
  'Urban vegetable garden and horticulture site: seasonal produce, subscription boxes, CSA schemes, and farm tours.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["vegetable-garden"]',
  '{"name": "vegetable-garden-urban-veg-garden", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "vegetable-garden", "category": "agricultural"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["horticulture", "nigeria-first", "organic", "urban-garden", "vegetable"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_palm_oil_trader_palm_oil_trader_site_v100',
  'palm-oil-trader-palm-oil-trader-site',
  'Palm Oil Producer / Trader',
  'Palm oil producer and trader site: product grades, bulk pricing, quality certifications, and export readiness.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["palm-oil-trader"]',
  '{"name": "palm-oil-trader-palm-oil-trader-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "palm-oil-trader", "category": "agricultural"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["agri-commodity", "export", "nigeria-first", "palm-oil", "trader"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_cocoa_exporter_cocoa_export_trader_v100',
  'cocoa-exporter-cocoa-export-trader',
  'Cocoa / Export Commodities Trader',
  'Cocoa and export commodities trader site: grade specifications, buyer registration, port logistics, and CACAO certifications.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["cocoa-exporter"]',
  '{"name": "cocoa-exporter-cocoa-export-trader", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "cocoa-exporter", "category": "agricultural"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["agri-commodity", "cocoa", "export", "nigeria-first", "trade"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_food_processing_food_processing_factory_v100',
  'food-processing-food-processing-factory',
  'Food Processing Factory',
  'Food processing factory site: product catalogue, NAFDAC numbers, production capacity, and distribution network.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["food-processing"]',
  '{"name": "food-processing-food-processing-factory", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "food-processing", "category": "agricultural"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["agri-business", "factory", "food-processing", "nafdac", "nigeria-first"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_community_radio_community_radio_site_v100',
  'community-radio-community-radio-site',
  'Community Radio / TV Station',
  'Community radio and TV station site: live stream, programme schedule, advertiser rates, and station profile.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["community-radio"]',
  '{"name": "community-radio-community-radio-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "community-radio", "category": "media"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["broadcast", "community-media", "nigeria-first", "radio", "tv"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_newspaper_distribution_newspaper_dist_ag_v100',
  'newspaper-distribution-newspaper-dist-agency',
  'Newspaper Distribution Agency',
  'Newspaper distribution agency site: titles distributed, coverage zones, subscription management, and vendor sign-up.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["newspaper-distribution"]',
  '{"name": "newspaper-distribution-newspaper-dist-agency", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "newspaper-distribution", "category": "media"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["distribution", "media", "newspaper", "nigeria-first", "print"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_land_surveyor_land_surveyor_site_v100',
  'land-surveyor-land-surveyor-site',
  'Land Surveyor / Registry Agent',
  'Land surveying and registry agent site: service types, SURCON registration, project portfolio, and contact.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["land-surveyor"]',
  '{"name": "land-surveyor-land-surveyor-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "land-surveyor", "category": "professional"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["land-surveyor", "nigeria-first", "property", "registry", "surveying"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_wedding_planner_wedding_planner_site_v100',
  'wedding-planner-wedding-planner-site',
  'Wedding Planner / Celebrant',
  'Wedding planning site: packages, vendor network, gallery, testimonials, and enquiry form.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["wedding-planner"]',
  '{"name": "wedding-planner-wedding-planner-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "wedding-planner", "category": "professional"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["celebrant", "events", "nigeria-first", "planner", "wedding"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_funeral_home_funeral_home_site_v100',
  'funeral-home-funeral-home-site',
  'Burial / Funeral Home',
  'Funeral home and burial services site: packages, chapel details, mortuary services, and family support.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["funeral-home"]',
  '{"name": "funeral-home-funeral-home-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "funeral-home", "category": "professional"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["burial", "funeral", "mortuary", "nigeria-first", "services"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_startup_startup_site_v100',
  'startup-startup-site',
  'Startup / Early-Stage Company',
  'Startup company site: product showcase, team profiles, investor deck access, and press kit.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["startup"]',
  '{"name": "startup-startup-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "startup", "category": "professional"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["early-stage", "innovation", "nigeria-first", "startup", "tech"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_pr_firm_pr_firm_site_v100',
  'pr-firm-pr-firm-site',
  'Public Relations Firm',
  'PR firm site: service capabilities, client portfolio, media contacts, and campaign case studies.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["pr-firm"]',
  '{"name": "pr-firm-pr-firm-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "pr-firm", "category": "professional"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["communications", "media", "nigeria-first", "pr", "public-relations"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_private_school_private_school_site_v100',
  'private-school-private-school-site',
  'Private School Operator',
  'Private school site: curriculum overview, admission process, fee schedule, WAEC/JAMB results, and parent portal.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["private-school"]',
  '{"name": "private-school-private-school-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "private-school", "category": "education"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["curriculum", "education", "nigeria-first", "private-school", "school"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_govt_school_govt_school_portal_v100',
  'govt-school-govt-school-portal',
  'Government School Management Portal',
  'Government school portal: staff directory, UBEC records, school statistics, and community updates.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["govt-school"]',
  '{"name": "govt-school-govt-school-portal", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "govt-school", "category": "education"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["education", "government", "nigeria-first", "school", "ubec"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_nursery_school_nursery_school_site_v100',
  'nursery-school-nursery-school-site',
  'Nursery / Early Childhood Centre',
  'Nursery and early childhood centre site: programme overview, fee guide, admission, and gallery.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["nursery-school"]',
  '{"name": "nursery-school-nursery-school-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "nursery-school", "category": "education"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["daycare", "early-childhood", "education", "nigeria-first", "nursery"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_community_health_community_health_site_v100',
  'community-health-community-health-site',
  'Community Health Worker Network',
  'CHW network site: health outreach programmes, referral directory, immunisation schedules, and volunteer sign-up.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["community-health"]',
  '{"name": "community-health-community-health-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "community-health", "category": "health"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["chw", "community-health", "health", "nigeria-first", "primary-care"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_rehab_centre_rehab_centre_site_v100',
  'rehab-centre-rehab-centre-site',
  'Rehabilitation / Recovery Centre',
  'Rehabilitation centre site: treatment programmes, facilities, admission process, and family resources.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["rehab-centre"]',
  '{"name": "rehab-centre-rehab-centre-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "rehab-centre", "category": "health"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["health", "mental-health", "nigeria-first", "recovery", "rehabilitation"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_elderly_care_elderly_care_facility_v100',
  'elderly-care-elderly-care-facility',
  'Elderly Care Facility',
  'Elderly care and nursing home site: care packages, facility tour, admission requirements, and family portal.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["elderly-care"]',
  '{"name": "elderly-care-elderly-care-facility", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "elderly-care", "category": "health"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["elderly-care", "geriatric", "health", "nigeria-first", "nursing-home"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_talent_agency_talent_agency_site_v100',
  'talent-agency-talent-agency-site',
  'Talent Agency / Model Agency',
  'Talent and model agency site: roster gallery, booking process, brand partnerships, and open call info.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["talent-agency"]',
  '{"name": "talent-agency-talent-agency-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "talent-agency", "category": "creator"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["agency", "creator", "model", "nigeria-first", "talent"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_recording_label_record_label_site_v100',
  'recording-label-record-label-site',
  'Record Label / Music Publisher',
  'Record label site: artist roster, discography, A&R contact, distribution partners, and press resources.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["recording-label"]',
  '{"name": "recording-label-record-label-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "recording-label", "category": "creator"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["label", "music", "nigeria-first", "publisher", "recording"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_podcast_studio_podcast_studio_site_v100',
  'podcast-studio-podcast-studio-site',
  'Podcast Studio / Audio Platform',
  'Podcast studio site: studio hire packages, production services, show listing, and advertising rates.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["podcast-studio"]',
  '{"name": "podcast-studio-podcast-studio-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "podcast-studio", "category": "creator"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["audio", "creator", "nigeria-first", "podcast", "studio"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_motivational_speaker_motivational_speake_v100',
  'motivational-speaker-motivational-speaker-site',
  'Motivational Speaker / Training Firm',
  'Speaker and training firm site: speaker profile, topic specialisations, booking enquiry, and testimonials.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["motivational-speaker"]',
  '{"name": "motivational-speaker-motivational-speaker-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "motivational-speaker", "category": "creator"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["coaching", "motivational", "nigeria-first", "speaker", "training"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_government_agency_govt_agency_portal_v100',
  'government-agency-govt-agency-portal',
  'Government Agency / Parastatal',
  'Government agency and parastatal portal: mandate, leadership, services directory, tenders, and public notices.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["government-agency"]',
  '{"name": "government-agency-govt-agency-portal", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "government-agency", "category": "institutional"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["agency", "government", "nigeria-first", "parastatal", "public-sector"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_events_centre_events_centre_rental_v100',
  'events-centre-events-centre-rental',
  'Events Centre / Hall Rental',
  'Events centre and hall rental site: capacity options, facilities, pricing packages, booking, and gallery.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["events-centre"]',
  '{"name": "events-centre-events-centre-rental", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "events-centre", "category": "place"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["events", "hall", "nigeria-first", "rental", "venue"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_restaurant_restaurant_menu_site_v100',
  'restaurant-restaurant-menu-site',
  'Restaurant Menu & Ordering Site',
  'Restaurant menu and ordering site: digital menu, daily specials, online ordering, and table reservation.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["restaurant"]',
  '{"name": "restaurant-restaurant-menu-site", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "restaurant", "category": "food-beverage"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["food", "menu", "nigeria-first", "ordering", "restaurant"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_tax_consultant_financial_services_v100',
  'tax-consultant-financial-services',
  'Tax Consultant / Revenue Agent',
  'Tax consultancy site: services overview, FIRS compliance, tax planning, and client onboarding.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["tax-consultant"]',
  '{"name": "tax-consultant-financial-services", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "tax-consultant", "category": "professional"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["accounting", "finance", "firs", "nigeria-first", "tax"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_tutoring_private_lessons_v100',
  'tutoring-private-lessons',
  'Tutoring / Private Lessons',
  'Private tutor and lesson teacher site: subjects, levels, rates, online/in-person options, and booking.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["tutoring"]',
  '{"name": "tutoring-private-lessons", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "tutoring", "category": "education"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["education", "lessons", "nigeria-first", "private", "tutoring"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_creche_early_childhood_v100',
  'creche-early-childhood',
  'Crèche / Day Care Centre',
  'Crèche and day care centre site: age groups, daily programme, fees, registration, and safety standards.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["creche"]',
  '{"name": "creche-early-childhood", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "creche", "category": "education"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["creche", "daycare", "early-childhood", "education", "nigeria-first"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_mobile_money_agent_fintech_v100',
  'mobile-money-agent-fintech',
  'Mobile Money / POS Agent Service',
  'Mobile money and POS agent service site: supported services, agent locations, commission structure, and agent sign-up.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["mobile-money-agent"]',
  '{"name": "mobile-money-agent-fintech", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "mobile-money-agent", "category": "financial"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["agent", "fintech", "mobile-money", "nigeria-first", "pos"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_bureau_de_change_fx_dealer_v100',
  'bureau-de-change-fx-dealer',
  'Bureau de Change / FX Dealer',
  'CBN-licensed bureau de change site: currencies traded, compliance info, and WhatsApp rate inquiry.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["bureau-de-change"]',
  '{"name": "bureau-de-change-fx-dealer", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "bureau-de-change", "category": "financial"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["bdc", "finance", "forex", "fx", "nigeria-first"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_hire_purchase_asset_finance_v100',
  'hire-purchase-asset-finance',
  'Hire Purchase / Asset Finance',
  'Hire purchase and asset finance site: product catalogue, deposit calculator, eligibility, and application.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["hire-purchase"]',
  '{"name": "hire-purchase-asset-finance", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "hire-purchase", "category": "financial"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["asset", "credit", "finance", "hire-purchase", "nigeria-first"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
),
(
  'tpl_p3_community_hall_civic_space_v100',
  'community-hall-civic-space',
  'Community Hall / Civic Space',
  'Community hall and civic space booking site: packages, facilities, availability calendar, and booking.',
  'website',
  '1.0.0',
  '^1.0.0',
  '["community-hall"]',
  '{"name": "community-hall-civic-space", "version": "1.0.0", "type": "website", "pillar": 3, "vertical": "community-hall", "category": "civic"}',
  NULL,
  'approved',
  1,
  0,
  0,
  '["civic", "community-hall", "events", "nigeria-first", "venue"]',
  '{}',
  '{}',
  '[]',
  '[]',
  unixepoch('now'),
  unixepoch('now')
)
;