-- Migration 0464b: SUPERSEDED — all columns already added by 0464a
--
-- HISTORY: This migration was originally planned as a second batch of schema bridge
-- columns for 0465-0543 seed migrations. However, 0464a was subsequently expanded
-- to include all required columns (label, confidence_tier, notes, dedup_key, etc.)
-- in a single batch.
--
-- Since 0464a already adds all the columns that 0464b originally targeted, running
-- 0464b's ALTER TABLE statements would produce "duplicate column name" errors.
--
-- This file is intentionally left as a no-op. The d1_migrations entry for
-- 0464b_seed_schema_extended_compat.sql is recorded to allow wrangler to advance
-- past this migration without error.
--
-- All required schema columns are present after 0464a runs.
-- See 0464a_seed_schema_label_compat.sql for the full list of added columns.
SELECT 1; -- no-op
