-- ============================================================
-- Migration 0487: OSM Nigeria Cooperatives
-- Generated: 2026-05-02 | Records: 30
-- Source: OpenStreetMap Nigeria — Cooperatives & Cooperative Societies
-- Idempotent: all inserts use INSERT OR IGNORE
-- ============================================================
INSERT OR IGNORE INTO seed_sources (id,label,source_type,url,confidence_tier,notes) VALUES ('seed_source_osm_cooperatives_ng_20260502','OpenStreetMap Nigeria — Cooperatives & Cooperative Societies','osm_extract','https://www.openstreetmap.org','seeded','OpenStreetMap ODbL licensed data');
INSERT OR IGNORE INTO seed_runs (id,label,phase,status,started_at,completed_at) VALUES ('seed_run_s10_osm_cooperatives_20260502','S10 OSM OSM Nigeria Cooperatives 2026-04-22','S07','completed',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_raw_artifacts (id,seed_run_id,artifact_type,file_path,content_hash,row_count,notes) VALUES ('seed_artifact_seed_run_s10_osm_cooperatives_20260502','seed_run_s10_osm_cooperatives_20260502','normalized','infra/db/seed/sources',NULL,30,'Auto-generated from OpenStreetMap Nigeria — Cooperatives & Cooperative Societies');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_47db2c15c36cda60','tenant_platform_seed','cooperative','Cooperation des Jeunes Bouchers','Cooperation des Jeunes Bouchers',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_47db2c15c36cda60','org_s10_cooperative_47db2c15c36cda60','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','Cooperation des Jeunes Bouchers',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_47db2c15c36cda60','prof_s10_cooperative_47db2c15c36cda60','Cooperation des Jeunes Bouchers','cooperation des jeunes bouchers cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_47db2c15c36cda60','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_47db2c15c36cda60','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_47db2c15c36cda60','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_47db2c15c36cda60','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_47db2c15c36cda60','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_47db2c15c36cda60','licence_data','{"osm_id": "11030106425", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_6629afb035247bc6','tenant_platform_seed','cooperative','CUMA Sutisua','CUMA Sutisua',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_6629afb035247bc6','org_s10_cooperative_6629afb035247bc6','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Sutisua',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_6629afb035247bc6','prof_s10_cooperative_6629afb035247bc6','CUMA Sutisua','cuma sutisua cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_6629afb035247bc6','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_6629afb035247bc6','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_6629afb035247bc6','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_6629afb035247bc6','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_6629afb035247bc6','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_6629afb035247bc6','licence_data','{"osm_id": "12989239886", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_8f47b2adcfaa107d','tenant_platform_seed','cooperative','CUMA Thuy 1','CUMA Thuy 1',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_8f47b2adcfaa107d','org_s10_cooperative_8f47b2adcfaa107d','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Thuy 1',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_8f47b2adcfaa107d','prof_s10_cooperative_8f47b2adcfaa107d','CUMA Thuy 1','cuma thuy 1 cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_8f47b2adcfaa107d','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_8f47b2adcfaa107d','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_8f47b2adcfaa107d','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_8f47b2adcfaa107d','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_8f47b2adcfaa107d','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_8f47b2adcfaa107d','licence_data','{"osm_id": "12991491072", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_c54312967a28f1c9','tenant_platform_seed','cooperative','CUMA Nonnin','CUMA Nonnin',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_c54312967a28f1c9','org_s10_cooperative_c54312967a28f1c9','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Nonnin',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_c54312967a28f1c9','prof_s10_cooperative_c54312967a28f1c9','CUMA Nonnin','cuma nonnin cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_c54312967a28f1c9','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_c54312967a28f1c9','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_c54312967a28f1c9','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_c54312967a28f1c9','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_c54312967a28f1c9','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_c54312967a28f1c9','licence_data','{"osm_id": "12991491224", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_f0f146554154e929','tenant_platform_seed','cooperative','CUMA Ina 4','CUMA Ina 4',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_f0f146554154e929','org_s10_cooperative_f0f146554154e929','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Ina 4',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_f0f146554154e929','prof_s10_cooperative_f0f146554154e929','CUMA Ina 4','cuma ina 4 cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_f0f146554154e929','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_f0f146554154e929','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_f0f146554154e929','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_f0f146554154e929','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_f0f146554154e929','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_f0f146554154e929','licence_data','{"osm_id": "12991491226", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_0fa5d57791637394','tenant_platform_seed','cooperative','CUMA Suu Non Nè','CUMA Suu Non Nè',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_0fa5d57791637394','org_s10_cooperative_0fa5d57791637394','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Suu Non Nè',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_0fa5d57791637394','prof_s10_cooperative_0fa5d57791637394','CUMA Suu Non Nè','cuma suu non nè cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_0fa5d57791637394','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_0fa5d57791637394','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_0fa5d57791637394','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_0fa5d57791637394','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_0fa5d57791637394','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_0fa5d57791637394','licence_data','{"osm_id": "12991491231", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_6e20b5aa00f758de','tenant_platform_seed','cooperative','CUMA Nannin','CUMA Nannin',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_6e20b5aa00f758de','org_s10_cooperative_6e20b5aa00f758de','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Nannin',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_6e20b5aa00f758de','prof_s10_cooperative_6e20b5aa00f758de','CUMA Nannin','cuma nannin cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_6e20b5aa00f758de','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_6e20b5aa00f758de','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_6e20b5aa00f758de','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_6e20b5aa00f758de','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_6e20b5aa00f758de','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_6e20b5aa00f758de','licence_data','{"osm_id": "12991491234", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_144491ad151f2fe3','tenant_platform_seed','cooperative','CUMA 2 Kilos','CUMA 2 Kilos',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_144491ad151f2fe3','org_s10_cooperative_144491ad151f2fe3','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA 2 Kilos',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_144491ad151f2fe3','prof_s10_cooperative_144491ad151f2fe3','CUMA 2 Kilos','cuma 2 kilos cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_144491ad151f2fe3','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_144491ad151f2fe3','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_144491ad151f2fe3','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_144491ad151f2fe3','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_144491ad151f2fe3','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_144491ad151f2fe3','licence_data','{"osm_id": "12991491246", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_bd11f1c2b4f12f22','tenant_platform_seed','cooperative','CUMA N''kossa','CUMA N''kossa',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_bd11f1c2b4f12f22','org_s10_cooperative_bd11f1c2b4f12f22','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA N''kossa',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_bd11f1c2b4f12f22','prof_s10_cooperative_bd11f1c2b4f12f22','CUMA N''kossa','cuma n''kossa cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_bd11f1c2b4f12f22','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_bd11f1c2b4f12f22','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_bd11f1c2b4f12f22','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_bd11f1c2b4f12f22','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_bd11f1c2b4f12f22','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_bd11f1c2b4f12f22','licence_data','{"osm_id": "12991491247", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_d4787acdf33cfd88','tenant_platform_seed','cooperative','CUMA Ina 3','CUMA Ina 3',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_d4787acdf33cfd88','org_s10_cooperative_d4787acdf33cfd88','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Ina 3',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_d4787acdf33cfd88','prof_s10_cooperative_d4787acdf33cfd88','CUMA Ina 3','cuma ina 3 cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_d4787acdf33cfd88','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_d4787acdf33cfd88','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_d4787acdf33cfd88','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_d4787acdf33cfd88','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_d4787acdf33cfd88','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_d4787acdf33cfd88','licence_data','{"osm_id": "12991491252", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_9fe39765ec4c208b','tenant_platform_seed','cooperative','CUMA Anti Sua An.Koua An Mon','CUMA Anti Sua An.Koua An Mon',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_9fe39765ec4c208b','org_s10_cooperative_9fe39765ec4c208b','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Anti Sua An.Koua An Mon',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_9fe39765ec4c208b','prof_s10_cooperative_9fe39765ec4c208b','CUMA Anti Sua An.Koua An Mon','cuma anti sua an.koua an mon cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_9fe39765ec4c208b','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_9fe39765ec4c208b','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_9fe39765ec4c208b','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_9fe39765ec4c208b','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_9fe39765ec4c208b','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_9fe39765ec4c208b','licence_data','{"osm_id": "12991491265", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_89b4f9aa1be8d557','tenant_platform_seed','cooperative','CUMA Anti Sua','CUMA Anti Sua',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_89b4f9aa1be8d557','org_s10_cooperative_89b4f9aa1be8d557','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Anti Sua',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_89b4f9aa1be8d557','prof_s10_cooperative_89b4f9aa1be8d557','CUMA Anti Sua','cuma anti sua cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_89b4f9aa1be8d557','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_89b4f9aa1be8d557','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_89b4f9aa1be8d557','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_89b4f9aa1be8d557','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_89b4f9aa1be8d557','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_89b4f9aa1be8d557','licence_data','{"osm_id": "12991491268", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_df893de834fb8c29','tenant_platform_seed','cooperative','CUMA Yidi wadi','CUMA Yidi wadi',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_df893de834fb8c29','org_s10_cooperative_df893de834fb8c29','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Yidi wadi',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_df893de834fb8c29','prof_s10_cooperative_df893de834fb8c29','CUMA Yidi wadi','cuma yidi wadi cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_df893de834fb8c29','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_df893de834fb8c29','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_df893de834fb8c29','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_df893de834fb8c29','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_df893de834fb8c29','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_df893de834fb8c29','licence_data','{"osm_id": "12991491271", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_6613ce27b7a0f0c1','tenant_platform_seed','cooperative','CUMA Tonwan Uti','CUMA Tonwan Uti',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_6613ce27b7a0f0c1','org_s10_cooperative_6613ce27b7a0f0c1','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Tonwan Uti',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_6613ce27b7a0f0c1','prof_s10_cooperative_6613ce27b7a0f0c1','CUMA Tonwan Uti','cuma tonwan uti cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_6613ce27b7a0f0c1','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_6613ce27b7a0f0c1','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_6613ce27b7a0f0c1','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_6613ce27b7a0f0c1','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_6613ce27b7a0f0c1','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_6613ce27b7a0f0c1','licence_data','{"osm_id": "12991491280", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_995fb6b1fe38829c','tenant_platform_seed','cooperative','CUMA Yaadu Yeeso','CUMA Yaadu Yeeso',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_995fb6b1fe38829c','org_s10_cooperative_995fb6b1fe38829c','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Yaadu Yeeso',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_995fb6b1fe38829c','prof_s10_cooperative_995fb6b1fe38829c','CUMA Yaadu Yeeso','cuma yaadu yeeso cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_995fb6b1fe38829c','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_995fb6b1fe38829c','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_995fb6b1fe38829c','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_995fb6b1fe38829c','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_995fb6b1fe38829c','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_995fb6b1fe38829c','licence_data','{"osm_id": "12991491284", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_714551bcb939895f','tenant_platform_seed','cooperative','CUMA Sutiisua','CUMA Sutiisua',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_714551bcb939895f','org_s10_cooperative_714551bcb939895f','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Sutiisua',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_714551bcb939895f','prof_s10_cooperative_714551bcb939895f','CUMA Sutiisua','cuma sutiisua cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_714551bcb939895f','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_714551bcb939895f','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_714551bcb939895f','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_714551bcb939895f','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_714551bcb939895f','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_714551bcb939895f','licence_data','{"osm_id": "12991491285", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_0b92d79847d1f223','tenant_platform_seed','cooperative','CUMA Su Non Tia Ko','CUMA Su Non Tia Ko',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_0b92d79847d1f223','org_s10_cooperative_0b92d79847d1f223','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Su Non Tia Ko',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_0b92d79847d1f223','prof_s10_cooperative_0b92d79847d1f223','CUMA Su Non Tia Ko','cuma su non tia ko cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_0b92d79847d1f223','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_0b92d79847d1f223','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_0b92d79847d1f223','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_0b92d79847d1f223','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_0b92d79847d1f223','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_0b92d79847d1f223','licence_data','{"osm_id": "12991491287", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_f842972dd3dc0c6a','tenant_platform_seed','cooperative','CUMA Grenier du Bénin','CUMA Grenier du Bénin',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_f842972dd3dc0c6a','org_s10_cooperative_f842972dd3dc0c6a','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Grenier du Bénin',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_f842972dd3dc0c6a','prof_s10_cooperative_f842972dd3dc0c6a','CUMA Grenier du Bénin','cuma grenier du bénin cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_f842972dd3dc0c6a','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_f842972dd3dc0c6a','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_f842972dd3dc0c6a','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_f842972dd3dc0c6a','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_f842972dd3dc0c6a','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_f842972dd3dc0c6a','licence_data','{"osm_id": "12991491289", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_d689eb1821c6e119','tenant_platform_seed','cooperative','CUMA Wanru Suru','CUMA Wanru Suru',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_d689eb1821c6e119','org_s10_cooperative_d689eb1821c6e119','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Wanru Suru',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_d689eb1821c6e119','prof_s10_cooperative_d689eb1821c6e119','CUMA Wanru Suru','cuma wanru suru cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_d689eb1821c6e119','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_d689eb1821c6e119','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_d689eb1821c6e119','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_d689eb1821c6e119','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_d689eb1821c6e119','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_d689eb1821c6e119','licence_data','{"osm_id": "12991491294", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_7f6934a4f7ddc9d1','tenant_platform_seed','cooperative','CUMA Pèdè','CUMA Pèdè',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_7f6934a4f7ddc9d1','org_s10_cooperative_7f6934a4f7ddc9d1','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Pèdè',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_7f6934a4f7ddc9d1','prof_s10_cooperative_7f6934a4f7ddc9d1','CUMA Pèdè','cuma pèdè cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_7f6934a4f7ddc9d1','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_7f6934a4f7ddc9d1','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_7f6934a4f7ddc9d1','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_7f6934a4f7ddc9d1','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_7f6934a4f7ddc9d1','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_7f6934a4f7ddc9d1','licence_data','{"osm_id": "12991491297", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_67c99f909025086a','tenant_platform_seed','cooperative','CUMA Non Ga Nera','CUMA Non Ga Nera',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_67c99f909025086a','org_s10_cooperative_67c99f909025086a','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Non Ga Nera',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_67c99f909025086a','prof_s10_cooperative_67c99f909025086a','CUMA Non Ga Nera','cuma non ga nera cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_67c99f909025086a','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_67c99f909025086a','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_67c99f909025086a','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_67c99f909025086a','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_67c99f909025086a','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_67c99f909025086a','licence_data','{"osm_id": "12991491298", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_bdb6a5a9a8b6d6fa','tenant_platform_seed','cooperative','CUMA Kinassi','CUMA Kinassi',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_bdb6a5a9a8b6d6fa','org_s10_cooperative_bdb6a5a9a8b6d6fa','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Kinassi',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_bdb6a5a9a8b6d6fa','prof_s10_cooperative_bdb6a5a9a8b6d6fa','CUMA Kinassi','cuma kinassi cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_bdb6a5a9a8b6d6fa','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_bdb6a5a9a8b6d6fa','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_bdb6a5a9a8b6d6fa','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_bdb6a5a9a8b6d6fa','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_bdb6a5a9a8b6d6fa','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_bdb6a5a9a8b6d6fa','licence_data','{"osm_id": "12991491300", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_23243347d4b5fc82','tenant_platform_seed','cooperative','CUMA Nannin','CUMA Nannin',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_23243347d4b5fc82','org_s10_cooperative_23243347d4b5fc82','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Nannin',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_23243347d4b5fc82','prof_s10_cooperative_23243347d4b5fc82','CUMA Nannin','cuma nannin cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_23243347d4b5fc82','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_23243347d4b5fc82','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_23243347d4b5fc82','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_23243347d4b5fc82','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_23243347d4b5fc82','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_23243347d4b5fc82','licence_data','{"osm_id": "12991491301", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_9077739b0dcd9d8b','tenant_platform_seed','cooperative','CUMA La Panthère','CUMA La Panthère',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_9077739b0dcd9d8b','org_s10_cooperative_9077739b0dcd9d8b','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA La Panthère',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_9077739b0dcd9d8b','prof_s10_cooperative_9077739b0dcd9d8b','CUMA La Panthère','cuma la panthère cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_9077739b0dcd9d8b','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_9077739b0dcd9d8b','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_9077739b0dcd9d8b','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_9077739b0dcd9d8b','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_9077739b0dcd9d8b','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_9077739b0dcd9d8b','licence_data','{"osm_id": "12991491308", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_475b2eaa5a914ce1','tenant_platform_seed','cooperative','CUMA Soudomsé','CUMA Soudomsé',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_475b2eaa5a914ce1','org_s10_cooperative_475b2eaa5a914ce1','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Soudomsé',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_475b2eaa5a914ce1','prof_s10_cooperative_475b2eaa5a914ce1','CUMA Soudomsé','cuma soudomsé cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_475b2eaa5a914ce1','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_475b2eaa5a914ce1','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_475b2eaa5a914ce1','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_475b2eaa5a914ce1','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_475b2eaa5a914ce1','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_475b2eaa5a914ce1','licence_data','{"osm_id": "12991491313", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_9bf4a3f707c422f0','tenant_platform_seed','cooperative','CUMA Nonganera','CUMA Nonganera',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_9bf4a3f707c422f0','org_s10_cooperative_9bf4a3f707c422f0','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Nonganera',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_9bf4a3f707c422f0','prof_s10_cooperative_9bf4a3f707c422f0','CUMA Nonganera','cuma nonganera cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_9bf4a3f707c422f0','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_9bf4a3f707c422f0','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_9bf4a3f707c422f0','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_9bf4a3f707c422f0','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_9bf4a3f707c422f0','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_9bf4a3f707c422f0','licence_data','{"osm_id": "12991491315", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_a98776e730e49cf4','tenant_platform_seed','cooperative','CUMA Antii Sua','CUMA Antii Sua',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_a98776e730e49cf4','org_s10_cooperative_a98776e730e49cf4','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Antii Sua',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_a98776e730e49cf4','prof_s10_cooperative_a98776e730e49cf4','CUMA Antii Sua','cuma antii sua cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_a98776e730e49cf4','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_a98776e730e49cf4','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_a98776e730e49cf4','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_a98776e730e49cf4','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_a98776e730e49cf4','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_a98776e730e49cf4','licence_data','{"osm_id": "12991491321", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_49eff407713a0da7','tenant_platform_seed','cooperative','CUMA Antii sua','CUMA Antii sua',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_49eff407713a0da7','org_s10_cooperative_49eff407713a0da7','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Antii sua',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_49eff407713a0da7','prof_s10_cooperative_49eff407713a0da7','CUMA Antii sua','cuma antii sua cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_49eff407713a0da7','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_49eff407713a0da7','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_49eff407713a0da7','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_49eff407713a0da7','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_49eff407713a0da7','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_49eff407713a0da7','licence_data','{"osm_id": "12991491322", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_9c9985e4ad8ad1aa','tenant_platform_seed','cooperative','CUMA Yeakana','CUMA Yeakana',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_9c9985e4ad8ad1aa','org_s10_cooperative_9c9985e4ad8ad1aa','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Yeakana',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_9c9985e4ad8ad1aa','prof_s10_cooperative_9c9985e4ad8ad1aa','CUMA Yeakana','cuma yeakana cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_9c9985e4ad8ad1aa','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_9c9985e4ad8ad1aa','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_9c9985e4ad8ad1aa','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_9c9985e4ad8ad1aa','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_9c9985e4ad8ad1aa','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_9c9985e4ad8ad1aa','licence_data','{"osm_id": "12991491327", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

INSERT OR IGNORE INTO organizations (id,tenant_id,organization_type,legal_name,display_name,registration_number,status,verification_state,created_at,updated_at) VALUES ('org_s10_cooperative_bee00f98348f0b57','tenant_platform_seed','cooperative','CUMA Non Nin','CUMA Non Nin',NULL,'active','seeded',unixepoch(),unixepoch());
INSERT OR IGNORE INTO profiles (id,subject_id,subject_type,primary_place_id,tenant_id,workspace_id,display_name,created_at,updated_at) VALUES ('prof_s10_cooperative_bee00f98348f0b57','org_s10_cooperative_bee00f98348f0b57','organization','place_nigeria_001','tenant_platform_seed','workspace_platform_seed_discovery','CUMA Non Nin',unixepoch(),unixepoch());
INSERT OR IGNORE INTO search_entries (id,profile_id,display_name,keywords,ancestry_path,vertical,created_at,updated_at) VALUES ('se_s10_cooperative_bee00f98348f0b57','prof_s10_cooperative_bee00f98348f0b57','CUMA Non Nin','cuma non nin cooperative society thrift savings nigeria','place_nigeria_001','cooperative',unixepoch(),unixepoch());
INSERT OR IGNORE INTO seed_ingestion_records (id,seed_run_id,entity_type,entity_id,source_id,status) VALUES ('ir_s10_cooperative_bee00f98348f0b57','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_bee00f98348f0b57','seed_source_osm_cooperatives_ng_20260502','ingested');
INSERT OR IGNORE INTO seed_entity_sources (id,seed_run_id,entity_type,entity_id,source_id,confidence_tier) VALUES ('es_s10_cooperative_bee00f98348f0b57','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_bee00f98348f0b57','seed_source_osm_cooperatives_ng_20260502','seeded');
INSERT OR IGNORE INTO seed_enrichment (id,seed_run_id,entity_type,entity_id,enrichment_type,enrichment_json) VALUES ('enr_s10_cooperative_bee00f98348f0b57','seed_run_s10_osm_cooperatives_20260502','organization','org_s10_cooperative_bee00f98348f0b57','licence_data','{"osm_id": "12991491329", "amenity": "", "addr_state": null, "denomination": null, "operator": null}');

