name = "webwaka-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

# ── Staging environment ───────────────────────────────────────────────────────
[env.staging]
name = "webwaka-api-staging"
workers_dev = false

routes = [
  { pattern = "api-staging.webwaka.com/*", zone_name = "webwaka.com" }
]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "webwaka-staging"
database_id = "7c264f00-c36d-4014-b2fe-c43e136e86f6"

[[env.staging.kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "2a81cd5b8d094911a20e1e0f6a190506"

[[env.staging.kv_namespaces]]
binding = "CACHE_KV"
id = "4732f3a682964607bae2170f350e4fb4"

[[env.staging.kv_namespaces]]
binding = "SESSIONS_KV"
id = "58bec07ac48448388b372c3dd8bc1bb9"

[env.staging.vars]
ENVIRONMENT = "staging"
LOG_LEVEL = "debug"

# ── Production environment ────────────────────────────────────────────────────
[env.production]
name = "webwaka-api-production"
workers_dev = false

routes = [
  { pattern = "api.webwaka.com/*", zone_name = "webwaka.com" }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "webwaka-production"
database_id = "72fa5ec8-52c2-4f41-b486-957d7b00c76f"

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "8cbf31285b0c43e1a8f44ee0af9fcdf3"

[[env.production.kv_namespaces]]
binding = "CACHE_KV"
id = "5bd5695d963247d0b105a936827e0a89"

[[env.production.kv_namespaces]]
binding = "SESSIONS_KV"
id = "86d90c013d3d4529ac08aad6d283a6bf"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "warn"

# ── Secrets (set via wrangler secret put, never in this file) ─────────────────
# JWT_SECRET
# INTER_SERVICE_SECRET
